-- Tests: minimap button, addon compartment and options menu.
---------------------------------------------------------------------------
test("a minimap button is made as soon as saved data loads (before login)", function()
    wow.load(FILES)
    wow.fire("ADDON_LOADED", "Keystance")
    local b = KeystanceMinimapButton
    assert(b, "made before PLAYER_LOGIN, so EllesmereUI's minimap can collect it")
    wow.fire("PLAYER_LOGIN")
    b.scripts.OnClick(b, "LeftButton")
    eq(KeystanceFrame:IsShown(), true)
    b.scripts.OnClick(b, "RightButton")
    eq(wow.menu.items[1].text, "Keystance", "right-click: options menu")
    b.scripts.OnEnter(b)
    eq(GameTooltip.lines[1][1], "Keystance")
end)

test("dragging moves the button around the minimap edge, and the position is kept", function()
    start(nil)
    local b = KeystanceMinimapButton
    b.scripts.OnDragStart(b)
    assert(b.scripts.OnUpdate, "follows the cursor while dragging")
    wow.mouse = { 1100, 600 } -- straight right of the minimap's centre
    b.scripts.OnUpdate(b)
    eq(KeystanceDB.settings.minimapAngle, 0)
    eq(b.point[4], 80); eq(b.point[5], 0, "on the edge: radius 70 + 10")
    b.scripts.OnDragStop(b)
    eq(b.scripts.OnUpdate, nil, "nothing runs once dropped")
end)

test("the minimap button can be hidden from the menu, and stays hidden next session", function()
    start(nil)
    Keystance_OnAddonCompartmentClick("Keystance", "RightButton", UIParent)
    local box = wow.menuItem("Show minimap button")
    eq(box.isSelected(), true)
    box.setSelected()
    eq(KeystanceMinimapButton:IsShown(), false)
    eq(KeystanceDB.settings.minimapHidden, true)
    local saved = KeystanceDB
    start(saved)
    eq(KeystanceMinimapButton, nil, "not even made")
    slash("minimap")
    eq(KeystanceMinimapButton:IsShown(), true, "turned back on: made now")
end)

test("the addon compartment entry opens the window, and its tooltip says how", function()
    start(nil)
    Keystance_OnAddonCompartmentClick("Keystance", "LeftButton", UIParent)
    eq(KeystanceFrame:IsShown(), true)
    Keystance_OnAddonCompartmentEnter("Keystance", UIParent)
    eq(GameTooltip.lines[1][1], "Keystance")
    Keystance_OnAddonCompartmentLeave()
    eq(GameTooltip:IsShown(), false)
end)

test("the options menu offers to open Keystance only while it's closed", function()
    start(nil)
    Keystance_OnAddonCompartmentClick("Keystance", "RightButton", UIParent)
    wow.menuItem("Open Keystance").fn()
    eq(KeystanceFrame:IsShown(), true)
    Keystance_OnAddonCompartmentClick("Keystance", "RightButton", UIParent)
    eq(wow.menuItem("Open Keystance"), nil)
end)

test("every menu option has a slash command listed in /kst help", function()
    start(nil)
    slash("help")
    -- Show minimap button: /kst minimap; Memory use: /kst mem; Open: /kst.
    assert(printed():find("/kst minimap", 1, true))
    assert(printed():find("mem", 1, true))
    assert(printed():find("/kst opens Keystance", 1, true))
end)
